sudo: false

language: android
android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    - extra-android-support
    - extra-android-m2repository

    # The BuildTools version used by the project
    - build-tools-23.0.2

    # The SDK version used to compile the project
    - android-22

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-17

script:
  - chmod +x gradlew
  - ./gradlew build
